# Operations Perfomed:
> 1. Reading in the Lower secondary school data
> 2. Rescaling the data to prevent data redundancy and to get optimal model performance
> 3. Hypertuning of models' performance for optimal model perfomance
> 4. Model building on the training datasets, evaluation on the testing sets using various regression techniques such as: Linear, Ridge, Lasso, and Gradient boost regression
> 5. Evaluation of models using various metrics in regression such as mean_absolute_error, mean_squared_error root_mean_squared_error, r2_score, residual_sum of squares to evaluate model performance
> 6. Performed comparison on the model between the actual values and the predicted values

In [ ]:
import pandas as pd
import pickle
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df= pd.read_csv('/content/Scaled_Lower_Secondary.csv_')

In [ ]:
df.head(3)

,Year,Completion Rate for lower secondary Edu,Childhood Education GER,"Gross enrolment ratio, early childhood educational development programmes","Gross intake ratio to the last grade of lower secondary general education,",Literacy rate for 25-64 years old,Expenditure on education as a percentage of total government expenditure (%),Government expenditure on education as a percentage of GDP (%),Central Asia,Central and Southern Asia,Eastern and South-Eastern Asia,Europe and Northern America,Latin America and the Caribbean,Northern Africa and Western Asia,Oceania,Southern Asia,Sub-Saharan Africa,Gender_numerical
0,2012,99.6,47.379975,5.868056,96.64,68.735,19.25,3.90,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,2012,99.3,47.379975,5.868056,97.66,68.735,19.25,3.90,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,2013,99.6,47.379975,5.868056,103.13,68.735,17.96,3.44,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

## Data Transformation

#### 1. Data Rescaling

In [ ]:
# Data Rescaling

data_col = df['Year']
df.set_index('Year',inplace =True)

df.head()

,Completion Rate for lower secondary Edu,Childhood Education GER,"Gross enrolment ratio, early childhood educational development programmes","Gross intake ratio to the last grade of lower secondary general education,",Literacy rate for 25-64 years old,Expenditure on education as a percentage of total government expenditure (%),Government expenditure on education as a percentage of GDP (%),Central Asia,Central and Southern Asia,Eastern and South-Eastern Asia,Europe and Northern America,Latin America and the Caribbean,Northern Africa and Western Asia,Oceania,Southern Asia,Sub-Saharan Africa,Gender_numerical
Year,,,,,,,,,,,,,,,,,
2012,99.6,47.379975,5.868056,96.64,68.735,19.25,3.90,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2012,99.3,47.379975,5.868056,97.66,68.735,19.25,3.90,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2013,99.6,47.379975,5.868056,103.13,68.735,17.96,3.44,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2013,99.4,47.379975,5.868056,102.95,68.735,17.96,3.44,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2014,99.6,36.650000,0.000000,105.74,68.735,17.32,3.42,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [ ]:
scaler = MinMaxScaler()
normalized_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
normalized_df['Year'] = data_col
normalized_df.set_index('Year', inplace =True)
normalized_df.head(3)

,Completion Rate for lower secondary Edu,Childhood Education GER,"Gross enrolment ratio, early childhood educational development programmes","Gross intake ratio to the last grade of lower secondary general education,",Literacy rate for 25-64 years old,Expenditure on education as a percentage of total government expenditure (%),Government expenditure on education as a percentage of GDP (%),Central Asia,Central and Southern Asia,Eastern and South-Eastern Asia,Europe and Northern America,Latin America and the Caribbean,Northern Africa and Western Asia,Oceania,Southern Asia,Sub-Saharan Africa,Gender_numerical
Year,,,,,,,,,,,,,,,,,
2012,0.995830,0.29137,0.062733,0.505572,0.657782,0.482729,0.286765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2012,0.992702,0.29137,0.062733,0.510908,0.657782,0.482729,0.286765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013,0.995830,0.29137,0.062733,0.539524,0.657782,0.446206,0.252941,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
normalized_df.corr().head(3)

,Completion Rate for lower secondary Edu,Childhood Education GER,"Gross enrolment ratio, early childhood educational development programmes","Gross intake ratio to the last grade of lower secondary general education,",Literacy rate for 25-64 years old,Expenditure on education as a percentage of total government expenditure (%),Government expenditure on education as a percentage of GDP (%),Central Asia,Central and Southern Asia,Eastern and South-Eastern Asia,Europe and Northern America,Latin America and the Caribbean,Northern Africa and Western Asia,Oceania,Southern Asia,Sub-Saharan Africa,Gender_numerical
Completion Rate for lower secondary Edu,1.000000,0.343942,0.32831,0.696288,0.340289,-0.045622,0.186643,0.201558,0.106305,0.060688,0.390367,0.157616,0.081599,0.087659,-0.014274,-0.657521,0.033615
Childhood Education GER,0.343942,1.000000,0.29785,0.360958,0.118688,-0.179933,-0.016032,-0.064723,0.087554,0.157975,0.185838,0.023716,-0.050977,0.053288,0.149977,-0.346649,0.001953
"Gross enrolment ratio, early childhood educational development programmes",0.328310,0.297850,1.00000,0.336662,0.122610,0.003044,-0.017530,-0.008402,-0.093543,0.091912,0.362503,0.144668,-0.110848,-0.091824,-0.105874,-0.196446,0.000421

In [ ]:
# spliting the dataset into training and testing set
x = normalized_df.drop('Completion Rate for lower secondary Edu', axis = 1)
y = normalized_df['Completion Rate for lower secondary Edu']


# making the train set to be 75% of the entire dataset.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=42)

# test is now 10% of the entire dataset
# validation is now 15% of the entire dataset

## Model Training, Testing and evaluation


 Because the target variable been 'Completion rate for primary school Edu' is a continoues data and not categorical. therfore, the model algorithm to be use is the regression and not classifiers.

#### 1. Linear Regression

In [ ]:
def parameters_hypertuning(model, parameters = {}):
  gs = GridSearchCV(model, parameters)
  gs.fit(x_train, y_train)
  hypertuned_parameters = gs.best_params_

  return hypertuned_parameters

In [ ]:
#hypertuning of paramters for the linear regression model
parameters_hypertuning(linear_model, {'n_jobs': range(0, 50, 5)})

{'n_jobs': 0}

In [ ]:
#hypertuning of paramters for the ridge model

parameters_hypertuning(ridge_model,
 {'alpha': np.arange(1.0, 20.0),
  'max_iter': range(0, 1500, 50)
  })

{'alpha': 1.0, 'max_iter': 50}

In [ ]:
#hypertuning of paramters for the lasso model
parameters_hypertuning(lasso_model, {'alpha': np.arange(1.0, 20.0),
  'max_iter': range(0, 1500, 50)})

{'alpha': 1.0, 'max_iter': 50}

In [ ]:
#hypertuning of paramters for the Gradient boosting model
parameters_hypertuning(Gbr, {'loss': ['squared_error', 'absolute_error', 'huber', 'quantile'],
                             'learning_rate': np.arange(1.0, 20.0, 2.0),
                             'n_estimators': range(0, 50, 5)})

{'learning_rate': 1.0, 'loss': 'squared_error', 'n_estimators': 45}

In [ ]:

import time

# Record start time
start_time = time.time()

# Create a Linear Regression model
linear_model = LinearRegression()

# Fit the model to the training dataset
linear_model.fit(x_train, y_train)

# Record end time
end_time = time.time()

# Calculate elapsed time
elapsed_time = end_time - start_time

# Display training time
print("Training took {:.2f} seconds.".format(elapsed_time))

Training took 0.04 seconds.

In [ ]:
# Obtain predictions
predicted_values = linear_model.predict(x_test)

#Getting the Linear model evaluation results
MAE = mean_absolute_error(y_test, predicted_values)
MSE = mean_squared_error(y_test, predicted_values)
RMSE =np.sqrt(mean_squared_error(y_test, predicted_values))
RSS =np.sum(np.square(y_test - predicted_values))
r2=r2_score(y_test, predicted_values)

In [ ]:
# Model evaluation

results = pd.DataFrame([['Linear regression', MAE, MSE, RMSE, RSS,r2]],
               columns = ['Model', 'MAE', 'MSE', 'RMSE', 'RSS','r2_score'])
results

               Model       MAE       MSE      RMSE        RSS  r2_score
0  Linear regression  0.126451  0.025388  0.159337  14.268137    0.7043

In [ ]:
lreg_df = pd.DataFrame(data ={"actual_values": y_test * 100, "predictions":predicted_values * 100})
lreg_df

      actual_values  predictions
Year
2016       7.631359    15.625000
2020      58.507089    58.984375
2018      25.562969    50.390625
2016      81.442869    90.234375
2015      98.227690    88.671875
...             ...          ...
2015      36.822352    54.687500
2018      98.748957    99.609375
2012      34.424520    30.859375
2020      37.552127    38.671875
2019      73.123436    84.375000

[562 rows x 2 columns]

## Ridge Regression

In [ ]:
# ridge regression
start_time = time.time()

ridge_model = Ridge(alpha = 1.0, max_iter = 50)
ridge_model.fit(x_train, y_train)
# Record end time
end_time = time.time()

# Calculate elapsed time
elapsed_time = end_time - start_time

# Display training time
print("Training took {:.2f} seconds.".format(elapsed_time))

Training took 0.02 seconds.

In [ ]:
y_preds = ridge_model.predict(x_test)

In [ ]:
#Getting the ridge model evaluation results
mae= mean_absolute_error(y_test, y_preds)
mse= mean_squared_error(y_test, y_preds)
rmse=np.sqrt(mean_squared_error(y_test, y_preds))
rss=np.sum(np.square(y_test - y_preds))
r_squared=r2_score(y_test, y_preds)

In [ ]:
model_results = pd.DataFrame([['Ridge regression', mae, mse, rmse, rss,r_squared]],
               columns = ['Model', 'MAE', 'MSE', 'RMSE', 'RSS','r2_score'])
results = pd.concat([results, model_results], ignore_index=True)
model_results

              Model       MAE      MSE      RMSE        RSS  r2_score
0  Ridge regression  0.126383  0.02536  0.159249  14.252524  0.704623

In [ ]:
ridg_df = pd.DataFrame(data ={"actual_values": y_test * 100, "predictions":predicted_values * 100})
ridg_df

      actual_values  predictions
Year
2016       7.631359    15.625000
2020      58.507089    58.984375
2018      25.562969    50.390625
2016      81.442869    90.234375
2015      98.227690    88.671875
...             ...          ...
2015      36.822352    54.687500
2018      98.748957    99.609375
2012      34.424520    30.859375
2020      37.552127    38.671875
2019      73.123436    84.375000

[562 rows x 2 columns]

#### Lasso regression

In [ ]:

# Record start time
start_time = time.time()

lasso_model = Lasso(alpha = 1.0, max_iter = 50)

lasso_model.fit(x_train, y_train)

# Record end time
end_time = time.time()

# Calculate elapsed time
elapsed_time = end_time - start_time

# Display training time
print("Training took {:.2f} seconds.".format(elapsed_time))

Training took 0.01 seconds.

In [ ]:
lasso_predictions  = lasso_model.predict(x_test)

In [ ]:
print(lasso_predictions.shape, y_test.shape)

(562,) (562,)

In [ ]:
# getting the lasso model evaluation results
lasso_r2 = r2_score(y_test, lasso_predictions)
lasso_mse = mean_squared_error( y_test,lasso_predictions)
lasso_rmse = np.sqrt(lasso_mse)
lasso_mae = mean_absolute_error(y_test,lasso_predictions)
lasso_rss = np.sum(np.square(y_test - lasso_predictions))

In [ ]:
model_results = pd.DataFrame([['lasso regression', lasso_mae, lasso_mse, lasso_rmse, lasso_rss, lasso_r2]],
               columns = ['Model', 'MAE', 'MSE', 'RMSE', 'RSS','r2_score'])
results = pd.concat([results, model_results], ignore_index=True)

In [ ]:
model_results

              Model      MAE       MSE      RMSE        RSS  r2_score
0  lasso regression  0.25994  0.085926  0.293131  48.290299 -0.000793

In [ ]:
lasso_df = pd.DataFrame(data ={"actual_values": y_test * 100, "predictions":lasso_predictions * 100})
lasso_df.sort_index(ascending=True, inplace=True)
lasso_df

      actual_values  predictions
Year
2012      15.867389    64.848649
2012      76.751460    64.848649
2012      98.436197    64.848649
2012      98.957465    64.848649
2012      82.631359    64.848649
...             ...          ...
2021      99.207673    64.848649
2021      99.020017    64.848649
2021      94.109675    64.848649
2021      97.581318    64.848649
2021      85.633862    64.848649

[562 rows x 2 columns]

#### GradientBoostingRegressor

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor


# Record start time
start_time = time.time()

Gbr = GradientBoostingRegressor(learning_rate= 1.0, loss= 'squared_error', n_estimators= 25)
Gbr.fit(x_train,y_train)

# Record end time
end_time = time.time()

# Calculate elapsed time
elapsed_time = end_time - start_time

# Display training time
print("Training took {:.2f} seconds.".format(elapsed_time))

Training took 0.06 seconds.

In [ ]:
Gbr_predictions  = Gbr.predict(x_test)

In [ ]:
# getting the Gradient boosting model results
Gbr_r2 = r2_score(y_test, Gbr_predictions)
Gbr_mse = mean_squared_error( y_test,Gbr_predictions)
Gbr_rmse = np.sqrt(Gbr_mse)
Gbr_mae = mean_absolute_error(y_test,Gbr_predictions)
Gbr_rss = np.sum(np.square(y_test - Gbr_predictions))

In [ ]:
model_results = pd.DataFrame([['GBR regression', Gbr_mae, Gbr_mse, Gbr_rmse, Gbr_rss, Gbr_r2]],
               columns = ['Model', 'MAE', 'MSE', 'RMSE', 'RSS','r2_score'])
results = pd.concat([results, model_results], ignore_index=True)

In [ ]:
model_results

            Model       MAE       MSE     RMSE       RSS  r2_score
0  GBR regression  0.083844  0.013787  0.11742  7.748509  0.839416

In [ ]:
Gbr_df = pd.DataFrame(data ={"actual_values": y_test * 100, "predictions":lasso_predictions * 100})
Gbr_df.sort_index(ascending=True, inplace=True)
Gbr_df

      actual_values  predictions
Year
2012      15.867389    64.848649
2012      76.751460    64.848649
2012      98.436197    64.848649
2012      98.957465    64.848649
2012      82.631359    64.848649
...             ...          ...
2021      99.207673    64.848649
2021      99.020017    64.848649
2021      94.109675    64.848649
2021      97.581318    64.848649
2021      85.633862    64.848649

[562 rows x 2 columns]

In [ ]:
# Printing the stored results of all the three models
results.drop_duplicates().head(4)

               Model       MAE       MSE      RMSE        RSS  r2_score
0  Linear regression  0.126451  0.025388  0.159337  14.268137  0.704300
1   Ridge regression  0.126383  0.025360  0.159249  14.252524  0.704623
2   lasso regression  0.259940  0.085926  0.293131  48.290299 -0.000793
3     GBR regression  0.083844  0.013787  0.117420   7.748509  0.839416

### conclusion
> Based on the results presented above, it is evident that the Ridge regression model exhibits the most favorable performance. This conclusion is drawn from the fact that the model achieves a mean_absolute_error of 0.1263. This value approaching zero signifies a strong indication of optimal performance within the context of regression modeling.

In [ ]:
def save_model(filename):
  filename=filename
  pickle.dump([linear_model, ridge_model, lasso_model, Gbr], open(filename, 'wb'))

In [ ]:
save_model('Lower_secondary_model.cav')